#!/usr/bin/env node
/*!
 * pqcbom-cli — TRELYAN Post-Quantum Readiness Scorecard CLI.
 * Usage: node pqcbom-cli.mjs [path] [--fail-on=broken-classical,quantum-broken] [--min-grade=B] [--json]
 * Writes: cbom.cdx.json (CycloneDX CBOM), quantum-readiness-report.md, pq-readiness-badge.json (shields endpoint).
 */
import { scanDirectory, toCycloneDX, toSARIF } from './pqcbom.mjs';
import { scorecardBadge, policyGate } from './pqcbom-server.mjs';
import { buildMigrationPlan, renderMigrationPlan } from './pqcbom-plan.mjs';
import { writeFileSync, existsSync, statSync } from 'fs';

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
  console.log(`pqcbom — TRELYAN Post-Quantum Readiness Scorecard CLI

Usage: node pqcbom-cli.mjs [path] [options]

  path                directory to scan (default: .)
  --fail-on=LIST      comma-separated risk classes that exit non-zero
                      (broken-classical,quantum-broken,quantum-weakened,classical-hybrid-ok,quantum-safe)
  --min-grade=A..F    exit non-zero below this grade
  --exclude=GLOBS     comma-separated path excludes (e.g. test-fixtures/,examples/,**/*.golden) —
                      also readable from .pqcbomignore lines containing '/' or prefixed 'path:';
                      excluded paths are COUNTED in the summary, never silently dropped
  --sarif[=PATH]      also write a SARIF 2.1.0 report (default: pqcbom.sarif) for GitHub code-scanning
  --plan[=PATH]       also write a sequenced PQC migration plan (default: migration-plan.md)
  --json              print the CycloneDX CBOM to stdout (suppress the human summary)
  --help, -h          show this help

Always writes: cbom.cdx.json, quantum-readiness-report.md, pq-readiness-badge.json (+ SARIF with --sarif, + the plan with --plan).
Lexical scan — findings are leads to verify, not a complete inventory. Unaudited reference tool.`);
  process.exit(0);
}
const dir = args.find((a) => !a.startsWith('-')) || '.';
// FAIL CLOSED on a bad target: a non-existent / non-directory path must NEVER
// silently scan nothing and then report a grade-A "all clear" (a false
// readiness attestation is the worst possible output of a trust tool).
if (!existsSync(dir) || !statSync(dir).isDirectory()) {
  console.error(`pqcbom: '${dir}' is not a directory. Usage: pqcbom [path] [options] (path defaults to '.', there is no 'scan' subcommand).`);
  process.exit(2);
}
const opt = (k) => { const a = args.find((x) => x.startsWith('--' + k + '=')); return a ? a.split('=')[1] : null; };
const failOn = (opt('fail-on') || '').split(',').filter(Boolean);
const minGrade = opt('min-grade');
const jsonOnly = args.includes('--json');
const sarifOut = args.includes('--sarif') ? 'pqcbom.sarif' : opt('sarif');   // --sarif -> default path; --sarif=PATH -> PATH
const planOut = args.includes('--plan') ? 'migration-plan.md' : opt('plan');  // --plan -> default path; --plan=PATH -> PATH
const excludePaths = (opt('exclude') || '').split(',').map((s) => s.trim()).filter(Boolean); // v0.10 path excludes

const RISK_EMOJI = { 'broken-classical': '⛔', 'quantum-broken': '🔴', 'quantum-weakened': '🟡', 'classical-hybrid-ok': '🔵', 'quantum-safe': '🟢' };
function mdReport(r) {
  const lines = [`# Post-Quantum Readiness Scorecard — Grade ${r.grade.letter} (${r.grade.score}/100)`, '', `**${r.grade.label}** · ${r.summary.files_scanned} files · ${r.summary.distinct_algorithms} distinct algorithms`, '',
    `| risk | count |`, `|---|---|`,
    `| ⛔ broken-classical | ${r.summary.broken_classical} |`, `| 🔴 quantum-broken | ${r.summary.quantum_broken} |`,
    `| 🟡 quantum-weakened | ${r.summary.quantum_weakened} |`, `| 🔵 classical (hybrid-ok) | ${r.summary.classical_hybrid_ok} |`,
    `| 🟢 quantum-resistant | ${r.summary.quantum_safe} |`, '', '## Findings & migration', '', `| risk | algorithm | file | rec |`, `|---|---|---|---|`];
  for (const f of r.findings.filter((x) => x.risk !== 'quantum-safe').slice(0, 100)) lines.push(`| ${RISK_EMOJI[f.risk]} | ${f.algo} | ${f.file}:${f.lines[0] ?? ''} | ${f.rec} |`);
  lines.push('', '_Generated by TRELYAN pqcbom (reference). Lexical scan — verify findings; production adds AST + cloud/cert/KMS discovery._');
  return lines.join('\n');
}

const report = await scanDirectory(dir, { excludePaths });
// A scan that examined ZERO files cannot attest readiness — refuse to emit a
// grade-A "all clear" for it (same false-attestation hazard as a bad path).
if (report.summary.files_scanned === 0) {
  console.error(`pqcbom: scanned 0 files under '${dir}' — no readiness grade emitted (nothing was examined). Check the path points at source code.`);
  process.exit(2);
}
if (jsonOnly) { console.log(JSON.stringify(toCycloneDX(report), null, 2)); }
else {
  console.log(`\n  Post-Quantum Readiness Scorecard: ${report.grade.letter}  (${report.grade.score}/100) — ${report.grade.label}`);
  console.log(`  ${report.summary.files_scanned} files · broken-classical ${report.summary.broken_classical} · quantum-broken ${report.summary.quantum_broken} · weakened ${report.summary.quantum_weakened} · hybrid-ok ${report.summary.classical_hybrid_ok} · resistant ${report.summary.quantum_safe}`);
  const nar = []; // transparency: a narrowed scan must SAY it was narrowed
  if (report.summary.excluded_paths) nar.push(`${report.summary.excluded_paths} path(s) excluded by policy (--exclude / .pqcbomignore)`);
  if (report.summary.skipped_outputs) nar.push(`${report.summary.skipped_outputs} pqcbom output artifact(s) skipped (never re-scanned)`);
  console.log(nar.length ? `  (${nar.join(' · ')})\n` : '');
}
writeFileSync('cbom.cdx.json', JSON.stringify(toCycloneDX(report), null, 2));
writeFileSync('quantum-readiness-report.md', mdReport(report));
writeFileSync('pq-readiness-badge.json', JSON.stringify(scorecardBadge(report.grade)));
if (sarifOut) writeFileSync(sarifOut, JSON.stringify(toSARIF(report, { baseDir: dir }), null, 2));
if (planOut) writeFileSync(planOut, '# PQC Migration Plan\n\n' + renderMigrationPlan(buildMigrationPlan(report)) + '\n');
if (!jsonOnly) console.log('  Wrote cbom.cdx.json, quantum-readiness-report.md, pq-readiness-badge.json' + (sarifOut ? ', ' + sarifOut : '') + (planOut ? ', ' + planOut : ''));

if (failOn.length || minGrade) {
  const gate = policyGate(report, { failOn, minGrade });
  if (!gate.pass) { console.error('  POLICY GATE FAILED: ' + gate.violations.join('; ')); process.exit(1); }
  if (!jsonOnly) console.log('  Policy gate: PASS');
}
