/*!
 * structural-corpus — measures the scanner against a CROSS-ECOSYSTEM corpus of crypto-usage patterns that defeat naive
 * lexical (bare-token) scanning: compound cipher-suite names, OpenSSL/JCA transform strings, .NET provider classes,
 * library spellings, OIDs. The corpus (test-fixtures/structural-corpus.json) was generated by a panel of per-ecosystem
 * agents (node/java/python/go/config/dotnet/php-ruby), each case labelled with expected algorithms + risk class +
 * whether it is STATICALLY detectable (honest: runtime/config-selected algorithms are NOT — they are blind spots).
 *
 * HONEST FRAMING: this is a self-assessment against a corpus WE publish (it is right here — critique it), not an
 * independent third-party benchmark. The headline metric is "did the scanner flag a VULNERABLE algorithm in this
 * snippet" (robust to the corpus's own debatable per-algo risk labels); a secondary metric checks risk-class agreement.
 * Regression guard: exits non-zero if static-detectable coverage falls below the pinned floor. Run: node structural-corpus.mjs
 */
import { scanText } from './pqcbom.mjs';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const CORPUS = JSON.parse(readFileSync(join(here, 'test-fixtures', 'structural-corpus.json'), 'utf8'));
const VULN = new Set(['broken-classical', 'quantum-broken', 'quantum-weakened']);
const EXT = { javascript: 'js', java: 'java', python: 'py', go: 'go', csharp: 'cs', php: 'php', ruby: 'rb', bash: 'sh', nginx: 'conf', apache: 'conf', 'sshd-config': 'conf', 'openssl-cnf': 'cnf', 'x509-pem': 'pem', yaml: 'yaml', haproxy: 'cfg' };

function evalCase(c) {
  const findings = scanText('case.' + (EXT[c.language] || 'txt'), c.snippet);
  const detectedRisks = new Set(findings.map((f) => f.risk));
  const expectedRisks = new Set((c.expected || []).map((e) => e.risk));
  const overlap = [...expectedRisks].filter((r) => detectedRisks.has(r));
  return {
    id: c.id, ecosystem: c.ecosystem, pattern_class: c.pattern_class, static: c.detectable_statically,
    why: c.why_lexical_misses,
    sawAny: findings.length > 0,
    sawVuln: findings.some((f) => VULN.has(f.risk)),                 // headline: did we flag a vulnerable algo?
    classFull: [...expectedRisks].every((r) => detectedRisks.has(r)),// every expected risk class present
    classAny: overlap.length > 0,
    detected: [...new Set(findings.map((f) => f.algo))],
  };
}

const results = CORPUS.map(evalCase);
const stat = results.filter((r) => r.static);
const runtime = results.filter((r) => !r.static);
const pct = (n, d) => (d ? (100 * n / d).toFixed(1) : '0.0') + '%';

const statSawVuln = stat.filter((r) => r.sawVuln).length;
const statClassFull = stat.filter((r) => r.classFull).length;
const statClassAny = stat.filter((r) => r.classAny).length;
const runtimeLeak = runtime.filter((r) => r.sawVuln).length; // runtime cases where a default/literal still leaked (bonus, not required)
const misses = stat.filter((r) => !r.sawVuln);

const byEco = {};
for (const r of results) { (byEco[r.ecosystem] ||= { s: 0, hit: 0 }); if (r.static) { byEco[r.ecosystem].s++; if (r.sawVuln) byEco[r.ecosystem].hit++; } }

const lines = [
  '# Structural / Compound-Identifier Coverage (self-assessment)',
  '',
  '> Measures the scanner against a cross-ecosystem corpus of crypto usage that **defeats naive bare-token scanning** — compound cipher-suite names, OpenSSL/JCA transform strings, .NET provider classes, OIDs. Corpus: `test-fixtures/structural-corpus.json` (generated by a per-ecosystem agent panel; right here, critique it). **Not** an independent third-party benchmark. Headline = "flagged a vulnerable algorithm in the snippet" (robust to debatable per-algo labels).',
  '',
  `**Corpus:** ${CORPUS.length} cases across ${Object.keys(byEco).length} ecosystems · ${stat.length} statically-detectable · ${runtime.length} honest runtime/config blind spots.`,
  '',
  '| Metric (statically-detectable cases) | Value |',
  '|---|---|',
  `| Flagged a vulnerable algorithm (headline) | **${statSawVuln}/${stat.length} = ${pct(statSawVuln, stat.length)}** |`,
  `| Risk-class agreement — all expected classes detected | ${statClassFull}/${stat.length} = ${pct(statClassFull, stat.length)} |`,
  `| Risk-class agreement — at least one expected class | ${statClassAny}/${stat.length} = ${pct(statClassAny, stat.length)} |`,
  '',
  '**Per ecosystem (vulnerable-flagged / statically-detectable):**',
  '',
  ...Object.entries(byEco).map(([e, v]) => `- ${e}: ${v.hit}/${v.s} = ${pct(v.hit, v.s)}`),
  '',
  `**Runtime/config blind spots:** ${runtime.length} cases are algorithm-by-runtime-value (env/config/reflection/string-concat) — genuinely undecidable from source. ${runtimeLeak} happened to leak a default literal we still flagged; the rest are honestly NOT detected (this is *why* findings are "leads to verify," not a complete inventory).`,
  '',
  misses.length ? '## Static-detectable cases we still MISS (honest)\n' + misses.map((m) => `- \`${m.id}\` (${m.ecosystem}, ${m.pattern_class}): ${m.why}`).join('\n') : '_Every statically-detectable case flags a vulnerable algorithm._',
  '',
  '_Reproduce: `node structural-corpus.mjs`. Lexical + compound-identifier scan; findings are leads to verify, not a complete inventory. SDK is an unaudited reference implementation._',
].join('\n');

try { writeFileSync(join(here, '..', '..', '..', 'program', 'products', 'STRUCTURAL_COVERAGE.md'), lines); } catch { /* program/ may be absent in a public clone — coverage still prints below */ }

console.log(`structural-corpus: vulnerable-flagged ${statSawVuln}/${stat.length} (${pct(statSawVuln, stat.length)}) static-detectable · class-agreement ${pct(statClassAny, stat.length)} · ${runtime.length} runtime blind spots · ${misses.length} static miss(es)`);
if (misses.length) misses.forEach((m) => console.log('  miss: ' + m.id + ' — ' + m.why.slice(0, 80)));

// Regression guard: the v0.7 compound layer brought static-detectable vulnerable-flag coverage to the floor below.
const FLOOR = 0.90; // pinned at 0.90 (v0.7 achieves 57/60 = 95%); raise as coverage improves, never silently lower
const rate = statSawVuln / (stat.length || 1);
if (rate < FLOOR) { console.error(`FAIL: static-detectable coverage ${pct(statSawVuln, stat.length)} < floor ${(FLOOR * 100).toFixed(0)}% (regression)`); if (typeof process !== 'undefined' && process.exit) process.exit(1); }
console.log('structural-corpus: OK (>= ' + (FLOOR * 100).toFixed(0) + '% floor)');
if (typeof process !== 'undefined' && process.exit) process.exit(0);
